### ISSUE TITLE
Add a screen for exporting badges for preprint

### ISSUE THREAD

**Issue by jashort** [kumoricon/registration#117]
- Choose type (VIP, staff, etc)
  - Use background? (Y/N)
  - Mark as preprinted? (Y/N) (update the value in attendee or staff tables)
  - Save to PDFs in /tmp?
  - Currently exports split up in batches of 100 pages for file size. Multithread it per file? For staff at least, would speed it up a lot

**Comment by belac9001** [comment]
(for myself)
todo:
- implement use background/mark as preprinted booleans
- implement Save to PDFs in /tmp? (will double check on what is meant by this, but the template i have currently set up is an input box allowing for different save path)
- optimize implementation/multithread maybe

**Comment by belac9001** [comment]
and probably clean up code

**Comment by jashort** [comment]
Resolved in #132
